-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 14:48:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web1` DEFAULT CHARACTER SET utf8 ;
USE `web1` ;

-- -----------------------------------------------------
-- Table `mydb`.`Avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web1`.`Avatar` (
  `idAvatar` INT NOT NULL AUTO_INCREMENT,
  `Pele` VARCHAR(45) NOT NULL,
  `Rosto` VARCHAR(45) NOT NULL,
  `Cabelo` VARCHAR(45) NOT NULL,
  `Torso` VARCHAR(45) NOT NULL,
  `Pernas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAvatar`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web1`.`Usuário` (
  `idUsuário` INT NOT NULL AUTO_INCREMENT,
  `Avatar_idAvatar` INT,
  `nome` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `dt_nascimento` DATE NULL,
  `Genero` VARCHAR(45) NULL,
  `nome_responsavel` VARCHAR(45) NULL,
  `tel_responsavel` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  CONSTRAINT `fk_Avatar_Usuario` FOREIGN KEY (`Avatar_idAvatar`) REFERENCES `web1`.`Avatar` (`idAvatar`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  PRIMARY KEY (`idUsuário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web1`.`Dentista` (
  `CRM` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`CRM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web1`.`Consulta` (
  `Usuário_idUsuário` INT NOT NULL,
  `Dentista_CRM` INT NOT NULL,
  PRIMARY KEY (`Usuário_idUsuário`, `Dentista_CRM`),
  INDEX `fk_Consulta_Dentista1_idx` (`Dentista_CRM` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Usuário` FOREIGN KEY (`Usuário_idUsuário`) REFERENCES `web1`.`Usuário` (`idUsuário`)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Dentista1` FOREIGN KEY (`Dentista_CRM`) REFERENCES `web1`.`Dentista` (`CRM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
